name: Build tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Docker
      run: curl https://get.docker.com | sh

    - name: Set tag name
      run: echo "REF=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV && echo "TAG=$(echo $REF | tr -dc '0-9\.')" >> $GITHUB_ENV

    - name: Build image
      run: docker build -t ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:$TAG .

    - name: Push image
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }} && docker push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:$TAG

