name: Build latest

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Docker
      run: curl https://get.docker.com | sh

    - name: Build image
      run: docker build -t ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:latest .

    - name: Push image
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }} && docker push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:latest

